[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-list_adapters",
  "allow-list_devices",
  "allow-list_paired_devices",
  "allow-set_adapter_powered",
  "allow-start_scan",
  "allow-stop_scan",
  "allow-connect_device",
  "allow-disconnect_device",
  "allow-get_device_info",
  "allow-bluetooth_plugin_status"
]
